eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: eurekaclient
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
        percentage: 1.0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123
#management:
#  security:
    #关闭安全验证，否则访问refresh端点时会提示权限不足
#    enabled: false
  